class Callback:
    def on_train_start(self, logs: dict) -> None: ...
    def on_train_end(self, logs: dict) -> None: ...
    def on_epoch_start(self, epoch: int, logs: dict) -> None: ...
    def on_epoch_end(self, epoch: int, logs: dict) -> None: ...
